### ISSUE TITLE
Change filepath management to Python's pathlib module

### ISSUE THREAD

**Issue by maosi100** [y-brehm/waveAlign#13]
Pathlib is superior to using the os's module functionality as it's platform independant.

**Comment by maosi100** [comment]
For reference see:

https://stackoverflow.com/questions/67112343/pathlib-vs-os-path-join-in-python

> pathlib is the more modern way since Python 3.4. The documentation for pathlib says that "For low-level path manipulation on strings, you can also use the os.path module."
> It doesn't make much difference for joining paths, but other path commands are more convenient with pathlib compared to os.path. For example, to get the "stem" (filename without extension):

Also:
https://betterprogramming.pub/should-you-be-using-pathlib-6f3a0fddec7e

I reckon that using pathlib would reduce overall code complexity for all file-management related activities.

**Comment by SimonZimmer** [comment]
@maosi100 
As discussed, I don't think platform-independence is the beating argument here, since `os` also provides that. (see `os.path.join` or `os.normpath`).
However, I do agree that pathlib seems to be more capable for other reasons like the `stem` function so I'd be down to convert 👍
