### ISSUE TITLE
Create caching mechanism

### ISSUE THREAD

**Issue by SimonZimmer** [y-brehm/waveAlign#18]
When new files are added to a rekordbox library, the user needs to reprocess all "old" files which should be avoided because:
1. takes a lot of time
2. introduces risk of degrading files at some point through encoding over and over again.

To avoid that, we need some kind of caching that is stored persistently on the users machine (like a log file)
When new files are introduced to the library, wavealign should recognise these files as "new", read their LUFS and then only process the new files.

**Comment by sabjorn** [comment]
@SimonZimmer could work with #19. Basically, the cache could be populated on first run through (calculate peak and lufs for each audio file). Then the second pass can move through each file in the cache.

**Comment by sabjorn** [comment]
@SimonZimmer i've started on the cache.

**Comment by y-brehm** [comment]
Closed with 8771374c50663b29389b1829cee3274637b56787
