### ISSUE TITLE
Automatic LUFS maximizer

### ISSUE THREAD

**Issue by SimonZimmer** [y-brehm/waveAlign#19]
When using wavealign, we usually do one read-only pass to determine manually how loud the target LUFS value can be for the given input folder.
This can become very unwieldy for big amounts of tracks (like an entire library)

We need an algorithm that will determine the maximum possible LUFS value automatically so the above described process is not necessary anymore.

**Comment by y-brehm** [comment]
Closed with 8771374c50663b29389b1829cee3274637b56787
