### ISSUE TITLE
Optimize logging

### ISSUE THREAD

**Issue by y-brehm** [y-brehm/waveAlign#28]
The python logging framework has a lot of functionality to offer. We currently implement our own logging and therefore re-invent the wheel a little. We should check what we can use and add from the logging framework.

**Comment by maosi100** [comment]
I can take this, only need some more detailed requirements on what we want wo achieve here.

**Comment by y-brehm** [comment]
https://github.com/y-brehm/waveAlign/pull/24#discussion_r1590121864

This is basically the discussion that I created the issue from. There just might be a nicer way of implementing logging, since the logging framework already provides functionality like e.g. creating a time-stamp.

Maybe @sabjorn has some more input on that?

**Comment by maosi100** [comment]
ade37b6
