### ISSUE TITLE
github actions

### ISSUE THREAD

**Issue by SimonZimmer** [y-brehm/waveAlign#5]
We should create a github actions build pipeline which automates the process of uploading the pip package to the public pypi server whenever a branch gets merged to `main`

**Comment by sabjorn** [comment]
@SimonZimmer started with https://github.com/y-brehm/waveAlign/pull/21 to get actions working initially

**Comment by y-brehm** [comment]
As this project is going to be moved soon, I'll close this issue as done. Basic github actions were implemented.
